categoria_index:
    path:     /
    defaults: { _controller: "IcoderJuegosBundle:CategoriasDeporte:index" }
    methods:  GET

categoria_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderJuegosBundle:CategoriasDeporte:show" }
    methods:  GET

categoria_new:
    path:     /new
    defaults: { _controller: "IcoderJuegosBundle:CategoriasDeporte:new" }
    methods:  [GET, POST]

categoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderJuegosBundle:CategoriasDeporte:edit" }
    methods:  [GET, POST]

categoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderJuegosBundle:CategoriasDeporte:delete" }
    methods:  DELETE
