deporte_index:
    path:     /
    defaults: { _controller: "IcoderJuegosBundle:Deporte:index" }
    methods:  GET

deporte_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderJuegosBundle:Deporte:show" }
    methods:  GET

deporte_new:
    path:     /new
    defaults: { _controller: "IcoderJuegosBundle:Deporte:new" }
    methods:  [GET, POST]

deporte_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderJuegosBundle:Deporte:edit" }
    methods:  [GET, POST]

deporte_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderJuegosBundle:Deporte:delete" }
    methods:  DELETE
