# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        IcoderBundle\Entity\user:
                 algorithm: bcrypt
                 cost: 4
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
                users:
                    user:
                        password: 123
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
            
        user_db:
            entity:
                class: IcoderBundle:user
                property: username
                
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    
    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false          
        
        main:
            anonymous: ~
            provider: user_db
            form_login:
                login_path: /user/login
                check_path: /user/login
            logout:
                path:   /user/logout
                target: /
                
    access_control:
      - { path: /user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: ROLE_USER }
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
                        
