canton_index:
    path:     /
    defaults: { _controller: "IcoderBundle:canton:index" }
    methods:  GET

canton_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderBundle:canton:show" }
    methods:  GET

canton_new:
    path:     /new
    defaults: { _controller: "IcoderBundle:canton:new" }
    methods:  [GET, POST]

canton_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderBundle:canton:edit" }
    methods:  [GET, POST]

canton_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderBundle:canton:delete" }
    methods:  DELETE
