sport_category_index:
    path:     /
    defaults: { _controller: "IcoderBundle:category:index" }
    methods:  GET

sport_category_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderBundle:category:show" }
    methods:  GET

sport_category_new:
    path:     /new
    defaults: { _controller: "IcoderBundle:category:new" }
    methods:  [GET, POST]

sport_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderBundle:category:edit" }
    methods:  [GET, POST]

sport_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderBundle:category:delete" }
    methods:  DELETE
