inscription_index:
    path:     /
    defaults: { _controller: "IcoderBundle:inscription:index" }
    methods:  GET

inscription_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderBundle:inscription:show" }
    methods:  GET

inscription_new:
    path:     /new
    defaults: { _controller: "IcoderBundle:inscription:new" }
    methods:  [GET, POST]

inscription_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderBundle:inscription:edit" }
    methods:  [GET, POST]

inscription_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderBundle:inscription:delete" }
    methods:  DELETE
