inscription_index:
    path:     /
    defaults: { _controller: "IcoderBundle:inscription:index" }
    methods:  GET

inscription_show:
    path:     /{id}/{error}/show
    defaults: { _controller: "IcoderBundle:inscription:show" }
    methods:  [GET, POST]

inscription_new:
    path:     /{id}/{test}/new
    defaults: { _controller: "IcoderBundle:inscription:new" }
    methods:  [GET, POST]

inscription_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderBundle:inscription:edit" }
    methods:  [GET, POST]

inscription_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderBundle:inscription:delete" }
    methods:  DELETE

inscription_add:
    path:     /add/canton
    defaults: { _controller: "IcoderBundle:inscription:add" }
    methods:  [GET, POST]
    
inscription_add_test:
    path:     /add/{id}/test
    defaults: { _controller: "IcoderBundle:inscription:addTest" }
    methods:  [GET, POST]