province_index:
    path:     /
    defaults: { _controller: "IcoderBundle:province:index" }
    methods:  GET

province_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderBundle:province:show" }
    methods:  GET

province_new:
    path:     /new
    defaults: { _controller: "IcoderBundle:province:new" }
    methods:  [GET, POST]
    
province_newSmall:
    path:     /newSmall
    defaults: { _controller: "IcoderBundle:province:newSmall" }
    methods:  [GET, POST]

province_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderBundle:province:edit" }
    methods:  [GET, POST]

province_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderBundle:province:delete" }
    methods:  DELETE
