test_index:
    path:     /
    defaults: { _controller: "IcoderBundle:SportTest:index" }
    methods:  GET

test_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderBundle:SportTest:show" }
    methods:  GET

test_new:
    path:     /new
    defaults: { _controller: "IcoderBundle:SportTest:new" }
    methods:  [GET, POST]

test_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderBundle:SportTest:edit" }
    methods:  [GET, POST]

test_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderBundle:SportTest:delete" }
    methods:  DELETE
