team_index:
    path:     /
    defaults: { _controller: "IcoderBundle:team:index" }
    methods:  GET

team_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderBundle:team:show" }
    methods:  GET

team_new:
    path:     /new
    defaults: { _controller: "IcoderBundle:team:new" }
    methods:  [GET, POST]

team_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderBundle:team:edit" }
    methods:  [GET, POST]

team_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderBundle:team:delete" }
    methods:  DELETE
