type_index:
    path:     /
    defaults: { _controller: "IcoderBundle:type:index" }
    methods:  GET

type_show:
    path:     /{id}/show
    defaults: { _controller: "IcoderBundle:type:show" }
    methods:  GET

type_new:
    path:     /new
    defaults: { _controller: "IcoderBundle:type:new" }
    methods:  [GET, POST]

type_edit:
    path:     /{id}/edit
    defaults: { _controller: "IcoderBundle:type:edit" }
    methods:  [GET, POST]

type_delete:
    path:     /{id}/delete
    defaults: { _controller: "IcoderBundle:type:delete" }
    methods:  DELETE
