icoder_juegos_deporte:
        resource: "@IcoderJuegosBundle/Resources/config/routing/deporte.yml"
        prefix:   /deporte

icoder_juegos_edicion:
        resource: "@IcoderJuegosBundle/Resources/config/routing/edicionjuegos.yml"
        prefix:   /edicion

icoder_juegos_categoria:
    resource: "@IcoderJuegosBundle/Resources/config/routing/categoriasdeporte.yml"
    prefix:   /categoria

icoder_juegos_homepage:
    path:     /
    defaults: { _controller: IcoderJuegosBundle:Default:index }
