<?php

namespace Icoder\JuegosBundle\Repository;

/**
 * CategoriasDeporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriasDeporteRepository extends \Doctrine\ORM\EntityRepository
{
}
