<?php

namespace Icoder\JuegosBundle\Repository;

/**
 * DeporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeporteRepository extends \Doctrine\ORM\EntityRepository
{
}
