<?php

namespace IcoderBundle\Repository;

/**
 * cantonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cantonRepository extends \Doctrine\ORM\EntityRepository
{
}
