<?php

namespace IcoderBundle\Repository;

/**
 * civilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class civilRepository extends \Doctrine\ORM\EntityRepository
{
}
