<?php

namespace IcoderBundle\Repository;

/**
 * competitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class competitorRepository extends \Doctrine\ORM\EntityRepository
{
}
