<?php

namespace IcoderBundle\Repository;

/**
 * editionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class editionRepository extends \Doctrine\ORM\EntityRepository
{
}
