<?php

namespace IcoderBundle\Repository;

/**
 * SportTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportTestRepository extends \Doctrine\ORM\EntityRepository
{
}
