<?php

namespace IcoderBundle\Repository;

/**
 * sportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sportRepository extends \Doctrine\ORM\EntityRepository
{
}
